name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ShelfMateProject/ShelfMate/ShelfMate.csproj

    - name: Build
      run: dotnet build ShelfMateProject/ShelfMate/ShelfMate.csproj --no-restore

    - name: Test
      run: dotnet test ShelfMateProject/ShelfMate.Tests/ShelfMate.Tests.csproj --no-build --verbosity normal

    - name: Run Application
      run: dotnet run --project ShelfMateProject/ShelfMate/ShelfMate.csproj
